/*
 * API REST EXTERNA de PinbalAdmin
 * Conjunt de Serveis REST de PinbalAdmin per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pinbaladmin.apiexterna.client.api;

import org.fundaciobit.pinbaladmin.apiexterna.client.services.ApiException;
import org.fundaciobit.pinbaladmin.apiexterna.client.model.RestExceptionInfo;
import org.fundaciobit.pinbaladmin.apiexterna.client.model.TramitSistraPojo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TramitSistraServiceApi
 */
public class TramitSistraServiceApiTest {

    private final TramitSistraServiceApi api = new TramitSistraServiceApi();

    /**
     * Retorna una transacció a partir de l&#39;identificador
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTransactionIDTest() throws ApiException {
        //
        //TramitSistraPojo tramitSistraPojo = null;
        //
        //String response = api.getTransactionID(tramitSistraPojo);

        // TODO: test validations
    }
}
