/*
 * API REST EXTERNA de PinbalAdmin
 * Conjunt de Serveis REST de PinbalAdmin per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pinbaladmin.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Lista parámetros (opcional)
 */
@JsonPropertyOrder({
  ParametrosApertura.JSON_PROPERTY_CODIGO,
  ParametrosApertura.JSON_PROPERTY_VALOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ParametrosApertura {
  public static final String JSON_PROPERTY_CODIGO = "codigo";
  private String codigo;

  public static final String JSON_PROPERTY_VALOR = "valor";
  private String valor;

  public ParametrosApertura() {
  }

  public ParametrosApertura codigo(String codigo) {
    
    this.codigo = codigo;
    return this;
  }

   /**
   * codigo
   * @return codigo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODIGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodigo() {
    return codigo;
  }


  @JsonProperty(JSON_PROPERTY_CODIGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }


  public ParametrosApertura valor(String valor) {
    
    this.valor = valor;
    return this;
  }

   /**
   * valor
   * @return valor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValor() {
    return valor;
  }


  @JsonProperty(JSON_PROPERTY_VALOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValor(String valor) {
    this.valor = valor;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParametrosApertura parametrosApertura = (ParametrosApertura) o;
    return Objects.equals(this.codigo, parametrosApertura.codigo) &&
        Objects.equals(this.valor, parametrosApertura.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, valor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParametrosApertura {\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

