/*
 * API REST EXTERNA de PinbalAdmin
 * Conjunt de Serveis REST de PinbalAdmin per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pinbaladmin.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Resultado
 */
@JsonPropertyOrder({
  Resultado.JSON_PROPERTY_ID_SESION_FORMULARIO,
  Resultado.JSON_PROPERTY_CANCELADO,
  Resultado.JSON_PROPERTY_XML,
  Resultado.JSON_PROPERTY_PDF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Resultado {
  public static final String JSON_PROPERTY_ID_SESION_FORMULARIO = "idSesionFormulario";
  private String idSesionFormulario;

  public static final String JSON_PROPERTY_CANCELADO = "cancelado";
  private Boolean cancelado;

  public static final String JSON_PROPERTY_XML = "xml";
  private String xml;

  public static final String JSON_PROPERTY_PDF = "pdf";
  private String pdf;

  public Resultado() {
  }

  public Resultado idSesionFormulario(String idSesionFormulario) {
    
    this.idSesionFormulario = idSesionFormulario;
    return this;
  }

   /**
   * Get idSesionFormulario
   * @return idSesionFormulario
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_SESION_FORMULARIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdSesionFormulario() {
    return idSesionFormulario;
  }


  @JsonProperty(JSON_PROPERTY_ID_SESION_FORMULARIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdSesionFormulario(String idSesionFormulario) {
    this.idSesionFormulario = idSesionFormulario;
  }


  public Resultado cancelado(Boolean cancelado) {
    
    this.cancelado = cancelado;
    return this;
  }

   /**
   * Get cancelado
   * @return cancelado
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELADO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancelado() {
    return cancelado;
  }


  @JsonProperty(JSON_PROPERTY_CANCELADO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelado(Boolean cancelado) {
    this.cancelado = cancelado;
  }


  public Resultado xml(String xml) {
    
    this.xml = xml;
    return this;
  }

   /**
   * Get xml
   * @return xml
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_XML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getXml() {
    return xml;
  }


  @JsonProperty(JSON_PROPERTY_XML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXml(String xml) {
    this.xml = xml;
  }


  public Resultado pdf(String pdf) {
    
    this.pdf = pdf;
    return this;
  }

   /**
   * Get pdf
   * @return pdf
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PDF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPdf() {
    return pdf;
  }


  @JsonProperty(JSON_PROPERTY_PDF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPdf(String pdf) {
    this.pdf = pdf;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resultado resultado = (Resultado) o;
    return Objects.equals(this.idSesionFormulario, resultado.idSesionFormulario) &&
        Objects.equals(this.cancelado, resultado.cancelado) &&
        Objects.equals(this.xml, resultado.xml) &&
        Objects.equals(this.pdf, resultado.pdf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idSesionFormulario, cancelado, xml, pdf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resultado {\n");
    sb.append("    idSesionFormulario: ").append(toIndentedString(idSesionFormulario)).append("\n");
    sb.append("    cancelado: ").append(toIndentedString(cancelado)).append("\n");
    sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
    sb.append("    pdf: ").append(toIndentedString(pdf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

