/*
 * API REST EXTERNA de PinbalAdmin
 * Conjunt de Serveis REST de PinbalAdmin per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pinbaladmin.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Usuario autenticado
 */
@JsonPropertyOrder({
  Usuario.JSON_PROPERTY_NIF,
  Usuario.JSON_PROPERTY_NOMBRE,
  Usuario.JSON_PROPERTY_APELLIDO1,
  Usuario.JSON_PROPERTY_APELLIDO2
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Usuario {
  public static final String JSON_PROPERTY_NIF = "nif";
  private String nif;

  public static final String JSON_PROPERTY_NOMBRE = "nombre";
  private String nombre;

  public static final String JSON_PROPERTY_APELLIDO1 = "apellido1";
  private String apellido1;

  public static final String JSON_PROPERTY_APELLIDO2 = "apellido2";
  private String apellido2;

  public Usuario() {
  }

  public Usuario nif(String nif) {
    
    this.nif = nif;
    return this;
  }

   /**
   * nif
   * @return nif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNif(String nif) {
    this.nif = nif;
  }


  public Usuario nombre(String nombre) {
    
    this.nombre = nombre;
    return this;
  }

   /**
   * Nombre
   * @return nombre
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNombre() {
    return nombre;
  }


  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNombre(String nombre) {
    this.nombre = nombre;
  }


  public Usuario apellido1(String apellido1) {
    
    this.apellido1 = apellido1;
    return this;
  }

   /**
   * Primer apellido
   * @return apellido1
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido1() {
    return apellido1;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido1(String apellido1) {
    this.apellido1 = apellido1;
  }


  public Usuario apellido2(String apellido2) {
    
    this.apellido2 = apellido2;
    return this;
  }

   /**
   * Segundo apellido
   * @return apellido2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido2() {
    return apellido2;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido2(String apellido2) {
    this.apellido2 = apellido2;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usuario usuario = (Usuario) o;
    return Objects.equals(this.nif, usuario.nif) &&
        Objects.equals(this.nombre, usuario.nombre) &&
        Objects.equals(this.apellido1, usuario.apellido1) &&
        Objects.equals(this.apellido2, usuario.apellido2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nif, nombre, apellido1, apellido2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Usuario {\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    apellido1: ").append(toIndentedString(apellido1)).append("\n");
    sb.append("    apellido2: ").append(toIndentedString(apellido2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

