
package es.caib.sistra.ws.v2.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SistraTipusProcedimentFacadeService", targetNamespace = "urn:es:caib:sistra:ws:v2:services", wsdlLocation = "META-INF/wsdl/SistraTipusProcedimentFacadeService.wsdl")
public class SistraTipusProcedimentFacadeService
    extends Service
{

    private final static URL SISTRATIPUSPROCEDIMENTFACADESERVICE_WSDL_LOCATION;
    private final static WebServiceException SISTRATIPUSPROCEDIMENTFACADESERVICE_EXCEPTION;
    private final static QName SISTRATIPUSPROCEDIMENTFACADESERVICE_QNAME = new QName("urn:es:caib:sistra:ws:v2:services", "SistraTipusProcedimentFacadeService");

    static {
        SISTRATIPUSPROCEDIMENTFACADESERVICE_WSDL_LOCATION = es.caib.sistra.ws.v2.services.SistraTipusProcedimentFacadeService.class.getClassLoader().getResource("META-INF/wsdl/SistraTipusProcedimentFacadeService.wsdl");
        WebServiceException e = null;
        if (SISTRATIPUSPROCEDIMENTFACADESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/SistraTipusProcedimentFacadeService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SISTRATIPUSPROCEDIMENTFACADESERVICE_EXCEPTION = e;
    }

    public SistraTipusProcedimentFacadeService() {
        super(__getWsdlLocation(), SISTRATIPUSPROCEDIMENTFACADESERVICE_QNAME);
    }

    public SistraTipusProcedimentFacadeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISTRATIPUSPROCEDIMENTFACADESERVICE_QNAME, features);
    }

    public SistraTipusProcedimentFacadeService(URL wsdlLocation) {
        super(wsdlLocation, SISTRATIPUSPROCEDIMENTFACADESERVICE_QNAME);
    }

    public SistraTipusProcedimentFacadeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISTRATIPUSPROCEDIMENTFACADESERVICE_QNAME, features);
    }

    public SistraTipusProcedimentFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SistraTipusProcedimentFacadeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SistraTipusProcedimentFacade
     */
    @WebEndpoint(name = "SistraTipusProcedimentFacade")
    public SistraTipusProcedimentFacade getSistraTipusProcedimentFacade() {
        return super.getPort(new QName("urn:es:caib:sistra:ws:v2:services", "SistraTipusProcedimentFacade"), SistraTipusProcedimentFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SistraTipusProcedimentFacade
     */
    @WebEndpoint(name = "SistraTipusProcedimentFacade")
    public SistraTipusProcedimentFacade getSistraTipusProcedimentFacade(WebServiceFeature... features) {
        return super.getPort(new QName("urn:es:caib:sistra:ws:v2:services", "SistraTipusProcedimentFacade"), SistraTipusProcedimentFacade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISTRATIPUSPROCEDIMENTFACADESERVICE_EXCEPTION!= null) {
            throw SISTRATIPUSPROCEDIMENTFACADESERVICE_EXCEPTION;
        }
        return SISTRATIPUSPROCEDIMENTFACADESERVICE_WSDL_LOCATION;
    }

}
