
package es.caib.sistra.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.caib.sistra.ws.v2.model.documentoconsulta.DocumentosConsulta;
import es.caib.sistra.ws.v2.model.formularioconsulta.FormulariosConsulta;
import es.caib.sistra.ws.v2.model.sistrafacade.ParametrosDominio;
import es.caib.sistra.ws.v2.model.valoresdominio.ValoresDominio;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SistraConsentimentFacade", targetNamespace = "urn:es:caib:sistra:ws:v2:services")
@XmlSeeAlso({
    es.caib.sistra.ws.v2.model.documentoconsulta.ObjectFactory.class,
    es.caib.sistra.ws.v2.model.formularioconsulta.ObjectFactory.class,
    es.caib.sistra.ws.v2.model.sistrafacade.ObjectFactory.class,
    es.caib.sistra.ws.v2.model.valoresdominio.ObjectFactory.class
})
public interface SistraConsentimentFacade {


    /**
     * 
     * @param id
     * @param parametros
     * @return
     *     returns es.caib.sistra.ws.v2.model.valoresdominio.ValoresDominio
     * @throws SistraFacadeException
     */
    @WebMethod
    @WebResult(name = "obtenerDominioReturn", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
    @RequestWrapper(localName = "obtenerDominio", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.sistra.ws.v2.model.sistrafacade.ObtenerDominio")
    @ResponseWrapper(localName = "obtenerDominioResponse", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.sistra.ws.v2.model.sistrafacade.ObtenerDominioResponse")
    public ValoresDominio obtenerDominio(
        @WebParam(name = "id", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        String id,
        @WebParam(name = "parametros", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        ParametrosDominio parametros)
        throws SistraFacadeException
    ;

    /**
     * 
     * @param identificadorTramite
     * @param forms
     * @return
     *     returns es.caib.sistra.ws.v2.model.documentoconsulta.DocumentosConsulta
     * @throws SistraFacadeException
     */
    @WebMethod
    @WebResult(name = "realizarConsultaReturn", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
    @RequestWrapper(localName = "realizarConsulta", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.sistra.ws.v2.model.sistrafacade.RealizarConsulta")
    @ResponseWrapper(localName = "realizarConsultaResponse", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.sistra.ws.v2.model.sistrafacade.RealizarConsultaResponse")
    public DocumentosConsulta realizarConsulta(
        @WebParam(name = "identificadorTramite", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        String identificadorTramite,
        @WebParam(name = "forms", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        FormulariosConsulta forms)
        throws SistraFacadeException
    ;

}
