
package es.caib.sistra.ws.v2.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SistraEntitatsFacadeService", targetNamespace = "urn:es:caib:sistra:ws:v2:services", wsdlLocation = "file:/D:/dades/dades/CarpetesPersonals/ProgramacioPortaFIB3/pinbaladmin2/pinbaladmin-ws/domini-sistra-api/pinbaladmin_ws_dominisistra_entitats.wsdl")
public class SistraEntitatsFacadeService
    extends Service
{

    private final static URL SISTRAENTITATSFACADESERVICE_WSDL_LOCATION;
    private final static WebServiceException SISTRAENTITATSFACADESERVICE_EXCEPTION;
    private final static QName SISTRAENTITATSFACADESERVICE_QNAME = new QName("urn:es:caib:sistra:ws:v2:services", "SistraEntitatsFacadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dades/dades/CarpetesPersonals/ProgramacioPortaFIB3/pinbaladmin2/pinbaladmin-ws/domini-sistra-api/pinbaladmin_ws_dominisistra_entitats.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISTRAENTITATSFACADESERVICE_WSDL_LOCATION = url;
        SISTRAENTITATSFACADESERVICE_EXCEPTION = e;
    }

    public SistraEntitatsFacadeService() {
        super(__getWsdlLocation(), SISTRAENTITATSFACADESERVICE_QNAME);
    }

    public SistraEntitatsFacadeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISTRAENTITATSFACADESERVICE_QNAME, features);
    }

    public SistraEntitatsFacadeService(URL wsdlLocation) {
        super(wsdlLocation, SISTRAENTITATSFACADESERVICE_QNAME);
    }

    public SistraEntitatsFacadeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISTRAENTITATSFACADESERVICE_QNAME, features);
    }

    public SistraEntitatsFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SistraEntitatsFacadeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SistraEntitatsFacade
     */
    @WebEndpoint(name = "SistraEntitatsFacade")
    public SistraEntitatsFacade getSistraEntitatsFacade() {
        return super.getPort(new QName("urn:es:caib:sistra:ws:v2:services", "SistraEntitatsFacade"), SistraEntitatsFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SistraEntitatsFacade
     */
    @WebEndpoint(name = "SistraEntitatsFacade")
    public SistraEntitatsFacade getSistraEntitatsFacade(WebServiceFeature... features) {
        return super.getPort(new QName("urn:es:caib:sistra:ws:v2:services", "SistraEntitatsFacade"), SistraEntitatsFacade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISTRAENTITATSFACADESERVICE_EXCEPTION!= null) {
            throw SISTRAENTITATSFACADESERVICE_EXCEPTION;
        }
        return SISTRAENTITATSFACADESERVICE_WSDL_LOCATION;
    }

}
