
package es.caib.sistra.ws.v2.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2018-05-08T09:26:09.496+02:00
 * Generated source version: 2.7.4
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
public class SistraFacadeException extends Exception {
    
    private es.caib.sistra.ws.v2.model.sistrafacade.SistraFacadeException fault;

    public SistraFacadeException() {
        super();
    }
    
    public SistraFacadeException(String message) {
        super(message);
    }
    
    public SistraFacadeException(String message, Throwable cause) {
        super(message, cause);
    }

    public SistraFacadeException(String message, es.caib.sistra.ws.v2.model.sistrafacade.SistraFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public SistraFacadeException(String message, es.caib.sistra.ws.v2.model.sistrafacade.SistraFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public es.caib.sistra.ws.v2.model.sistrafacade.SistraFacadeException getFaultInfo() {
        return this.fault;
    }
}
